# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP4/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP4)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,8fc8fc446668ffabebf18e204e2348620dc9f0b2)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,7d8342ca536c70767aa842d93b0fac562fd69da9)
$(call add-radio-file-sha1-checked,radio/modem.img,b99c0d6b1ff52fcb38c79176b5a9aa76def2c6d7)
$(call add-radio-file-sha1-checked,radio/abl.img,0c6b3151138c9a3ff4cf1f376cecd65b2c636dfa)
$(call add-radio-file-sha1-checked,radio/aop.img,a5a74b4114d335d67ed9ad22cda95801fc683734)
$(call add-radio-file-sha1-checked,radio/devcfg.img,f0ee3d94c88efce8014026b0b2c79e163086646d)
$(call add-radio-file-sha1-checked,radio/dsp.img,d3322252e7d63060e179e2407038474a84ef6026)
$(call add-radio-file-sha1-checked,radio/featenabler.img,a6a14747d3d51eb0b9d98107407935983c37917f)
$(call add-radio-file-sha1-checked,radio/hyp.img,38dfecc04ccb12afbe0528cbc05de6a568539ee5)
$(call add-radio-file-sha1-checked,radio/imagefv.img,bc0e1c3359e7d2a5145def0bc1d81aefa07af86a)
$(call add-radio-file-sha1-checked,radio/keymaster.img,4ecccf5fe54e52c006f2eec45d0eaada2c10fd90)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,0f3489fa82b7d86eefc07811b8e2699bc0dee80c)
$(call add-radio-file-sha1-checked,radio/qupfw.img,965718ad0f3bb36e66129a5f376d85032fa1d2a3)
$(call add-radio-file-sha1-checked,radio/tz.img,0ac8038fd5645085ce31e66250e48861fcd9cdac)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,d458a029a63b60e3cfc64487ac41cff1cd2b5e04)
$(call add-radio-file-sha1-checked,radio/xbl.img,710e45fb78b630700ccfcfe34e457a36bd78f362)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2595e5b4170cdd315544f026d7f327debcd5252f)

endif
