# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP4/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP4)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,6e5d123a30770fe453370ba9895f0441a6551017)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,ad026f8ab31717105f3abef6151171e7803be695)
$(call add-radio-file-sha1-checked,radio/modem.img,a91b3e7dc58f2ade9c74cab72f4633b2c2893373)
$(call add-radio-file-sha1-checked,radio/abl.img,3b4fa16aa6c1f051e91d60203f6739f2bdd35534)
$(call add-radio-file-sha1-checked,radio/aop.img,f1524aaa56c7963f66f167b1ea5aaf3434a45711)
$(call add-radio-file-sha1-checked,radio/devcfg.img,ac8e42fef5701001ad20e0502d6ec06737a4af7a)
$(call add-radio-file-sha1-checked,radio/dsp.img,d3322252e7d63060e179e2407038474a84ef6026)
$(call add-radio-file-sha1-checked,radio/featenabler.img,fc086313873852b989b195414c7a4d764d02b995)
$(call add-radio-file-sha1-checked,radio/hyp.img,b65edb64cbde142c9d33add60caede6888ae048e)
$(call add-radio-file-sha1-checked,radio/imagefv.img,26e4bd251d58dafeb946c0f413c9d18f9247904f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f32a6af24bbb16105c008acf7765bf118ad6b429)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,04152a1000f7554d5d55b34f5461427651955a96)
$(call add-radio-file-sha1-checked,radio/qupfw.img,a5832f1e2ca50d03da6c0bfaf315355a267a1730)
$(call add-radio-file-sha1-checked,radio/tz.img,7588384bedaf34f7568d240b02a415cb942fc5fe)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,2edd4617b0ec39dfa1bdadcdb702c7bc04ad1683)
$(call add-radio-file-sha1-checked,radio/xbl.img,7e39db5fe8cbec8d63639efa9c1c8c2c098ba684)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,e827d9f7fea29b33973a53ae2ab7d187ef8dfc39)

endif
